name: b
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '-g')"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Apply Patches
        continue-on-error: true
        run: |
          git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
          ./gradlew applyPatches
      - name: pack
        run: tar -czf src.tar.gz narashite-*
      - uses: actions/upload-artifact@v3
        with:
          name: 727
          path: src.tar.gz
